/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinalp;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author david
 */
public class Tarea11cargar extends javax.swing.JFrame {
    
        ArrayList<Usuario> usuarios = new ArrayList<>();


    /**
     * Creates new form Tarea11cargar
     */
    public Tarea11cargar() {
        initComponents();
        
 
        LlenarTabla();
    }
    
    private void LlenarTabla() {
        
        
        DefaultTableModel t = new DefaultTableModel(new String[]{"Nombre","Usuario","Password","Rol"},ProyectoFinalP.usuarios.size());
        vistaxml.setModel(t);
        
        TableModel tabla = vistaxml.getModel();
        
        for(int i = 0; i<ProyectoFinalP.usuarios.size();i++){
            Usuario u = ProyectoFinalP.usuarios.get(i);
            tabla.setValueAt(u.getNombre(), i, 0);
            tabla.setValueAt(u.getUsuario(), i, 1);
            tabla.setValueAt(u.getPassword(), i, 2);
            tabla.setValueAt(u.getRol(), i, 3);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        vistaxml = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaxml.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(vistaxml);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Archivo:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 36)); // NOI18N
        jLabel2.setText("Archivos XML");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel3.setText("Vista previa");

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        ProyectoFinalP.usuarios = new ArrayList<>(usuarios);
        
        JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter archivo = new FileNameExtensionFilter("Tareaxml11", "xml");
        
        abrir.setFileFilter(archivo);
        
        int abrirarchivo = abrir.showOpenDialog(this);
        
        if(abrirarchivo == JFileChooser.APPROVE_OPTION){
            File documento = abrir.getSelectedFile();
            leerxml(documento);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter archivo = new FileNameExtensionFilter("Tareaxml11", "xml");
        
        abrir.setFileFilter(archivo);
        
        int abrirarchivo = abrir.showOpenDialog(this);
        
        if(abrirarchivo == JFileChooser.APPROVE_OPTION){
            File documento = abrir.getSelectedFile();
            escribirxml(documento);
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void escribirxml(File documentoi){
        
        FileWriter scr = null;
        PrintWriter es = null;
        
        
        try{
            
            scr = new FileWriter(documentoi);
            es = new PrintWriter(scr);
            
            es.println("<usuarios>");
            
            for(Usuario u : ProyectoFinalP.usuarios){     
                
                es.println("<usuario>");
                
                es.println("<user>"+u.getUsuario()+"</user>");
                es.println("<nombre>"+u.getNombre()+"</nombre>");
                es.println("<password>"+u.getPassword()+"</password>");
                es.println("<rol>"+u.getRol()+"</rol>");
                
                es.println("</usuario>");

                
            }
            
            
            
            es.println("</usuarios>");

            
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        finally{
            try {
                if(scr!=null){
                    scr.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        
        
    }
    private void leerxml(File documento){
        
        try{
            DocumentBuilderFactory arch = DocumentBuilderFactory.newInstance();
            DocumentBuilder docm = arch.newDocumentBuilder();
            Document tarea = docm.parse(documento);
            
            tarea.getDocumentElement().normalize();
            
            NodeList usrList = tarea.getElementsByTagName("usuario");
            
            for(int i=0; i<usrList.getLength(); i++){
                
                Node usrNode = usrList.item(i);
                
                if(usrNode.getNodeType() == Node.ELEMENT_NODE){
                    
                    Element e = (Element) usrNode;
                    
                    Usuario u = new Usuario();
                    u.setUsuario(e.getElementsByTagName("user").item(0).getTextContent());
                    u.setNombre(e.getElementsByTagName("nombre").item(0).getTextContent());
                    u.setPassword(e.getElementsByTagName("password").item(0).getTextContent());
                    u.setRol(Integer.parseInt(e.getElementsByTagName("rol").item(0).getTextContent()));
                    
                    usuarios.add(u);
                    
                }

                
            }
            ProyectoFinalP.usuarios = new ArrayList<>(usuarios);
            
            LlenarTabla();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable vistaxml;
    // End of variables declaration//GEN-END:variables
}
