/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinalp;

import javax.swing.JOptionPane;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author david
 */
public class UsuariosCreados extends javax.swing.JFrame {
    
    private Usuario usuario;
    LinkedList<Usuario> usuarios = new LinkedList<>();
    
    

    public UsuariosCreados() {
        initComponents();
        
        
       pintarTabla();
       rol1.removeAllItems();
       rol1.addItem("Administrador");
       rol1.addItem("Vendedor");
}
private void pintarTabla(){
       
        
        DefaultTableModel t = new DefaultTableModel(new String[]{"Nombre","Usuario","Password","Rol"},ProyectoFinalP.usuarios.size());
        RegUsuarios.setModel(t);
        
        TableModel tabla = RegUsuarios.getModel();
        
        for(int i = 0; i<ProyectoFinalP.usuarios.size();i++){
            Usuario u = ProyectoFinalP.usuarios.get(i);
            tabla.setValueAt(u.getNombre(), i, 0);
            tabla.setValueAt(u.getUsuario(), i, 1);
            tabla.setValueAt(u.getPassword(), i, 2);
            tabla.setValueAt(u.getRol(), i, 3);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RegUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        usuario1 = new javax.swing.JTextField();
        password1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        rol1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RegUsuarios);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Usuario");

        jLabel3.setText("Password");

        jLabel4.setText("Rol");

        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rol1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rol1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Abrir xml");

        jButton5.setText("Abrir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Crear xml");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton4)
                                .addGap(175, 175, 175)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario1)
                                    .addComponent(nombre1)
                                    .addComponent(password1)
                                    .addComponent(rol1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jButton5))
                    .addComponent(jButton6))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int borrar = RegUsuarios.getSelectedRow();
    if(borrar>-1){
        if(borrar == 0){
               JOptionPane.showMessageDialog(this, "No puede eliminar al administrador");
            }
            else{
            
   
            if(JOptionPane.showConfirmDialog(this,"Esta seguro que desea eliminar?")==0){
            ProyectoFinalP.usuarios.remove(borrar);
            pintarTabla();
            JOptionPane.showMessageDialog(this, "Usuario eliminado");
            }
        }
    }
    else{
        JOptionPane.showMessageDialog(this, "Seleccione un usuario");
    }
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int modificar = RegUsuarios.getSelectedRow();
    if(modificar  >-1){
        
        usuario = ProyectoFinalP.usuarios.get(modificar);
        nombre1.setText(usuario.getNombre());
        usuario1.setText(usuario.getUsuario());
        password1.setText(usuario.getPassword());
        rol1.setSelectedIndex(usuario.getRol() -1);
    }
    else
        JOptionPane.showMessageDialog(this,"Seleccione un usuario para modificar");
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(usuario!=null){
        
        usuario.setNombre(nombre1.getText());
        usuario.setUsuario(usuario1.getText());
        usuario.setPassword(password1.getText());
        String rol = rol1.getSelectedItem().toString();
        
        if(rol.equals("Administrador")){
            usuario.setRol(1);
        }
        else{
            usuario.setRol(2);
        }
        pintarTabla();
        
        
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void rol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rol1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                
        JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter archivo = new FileNameExtensionFilter("Tareaxml11", "xml");
        
        abrir.setFileFilter(archivo);
        
        int abrirarchivo = abrir.showOpenDialog(this);
        
        if(abrirarchivo == JFileChooser.APPROVE_OPTION){
            File documento = abrir.getSelectedFile();
            escribirxml(documento);
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void escribirxml(File documento){
                
        FileWriter scr = null;
        PrintWriter es = null;
        
        
        try{
            
            scr = new FileWriter(documento);
            es = new PrintWriter(scr);
            
            es.println("<usuarios>");
            
            for(Usuario u : usuarios){     
                
                es.println("<usuario>");
                
                es.println("<user>"+u.getUsuario()+"</user>");
                es.println("<nombre>"+u.getNombre()+"</nombre>");
                es.println("<password>"+u.getPassword()+"</password>");
                es.println("<rol>"+u.getRol()+"</rol>");
                
                es.println("</usuario>");

                
            }
            
            
            
            es.println("</usuarios>");

            
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        finally{
            try {
                if(scr!=null){
                    scr.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            
        usuarios = new LinkedList<>();
        
        JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter archivo = new FileNameExtensionFilter("Tareaxml11", "xml");
        
        abrir.setFileFilter(archivo);
        
        int abrirarchivo = abrir.showOpenDialog(this);
        
        if(abrirarchivo == JFileChooser.APPROVE_OPTION){
            File documento = abrir.getSelectedFile();
            leerxml(documento);
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private void leerxml(File documento){
        
        try{
            DocumentBuilderFactory arch = DocumentBuilderFactory.newInstance();
            DocumentBuilder docm = arch.newDocumentBuilder();
            Document tarea = docm.parse(documento);
            
            tarea.getDocumentElement().normalize();
            
            NodeList usrList = tarea.getElementsByTagName("usuario");
            
            for(int i=0; i<usrList.getLength(); i++){
                
                Node usrNode = usrList.item(i);
                
                if(usrNode.getNodeType() == Node.ELEMENT_NODE){
                    
                    Element e = (Element) usrNode;
                    
                    Usuario u = new Usuario();
                    u.setUsuario(e.getElementsByTagName("user").item(0).getTextContent());
                    u.setNombre(e.getElementsByTagName("nombre").item(0).getTextContent());
                    u.setPassword(e.getElementsByTagName("password").item(0).getTextContent());
                    u.setRol(Integer.parseInt(e.getElementsByTagName("rol").item(0).getTextContent()));
                    
                    usuarios.add(u);
                    
                }

                
            }
            
            pintarTabla();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RegUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField password1;
    private javax.swing.JComboBox<String> rol1;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
